name: shopify-studio-app
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: npm start
  build_command: npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: JWT_SECRET
    value: your-super-secret-jwt-key-change-this-in-production
    type: SECRET
  - key: ADMIN_EMAIL
    value: admin@shopifystudio.ir
  - key: ADMIN_PASSWORD
    value: admin123
    type: SECRET
  - key: EMAIL_FROM
    value: noreply@shopifystudio.ir
  health_check:
    http_path: /api/status
  http_port: 8080
  routes:
  - path: /